const episodeMap = {
    1: { episodeNumber: 1, episodeName: "Meet Vanessa", fileName: "FINAL_BG_EPS01_Meet_Vanessa_transcript_with_speakers.txt", id: "5IilfJTUyEKzb3eCcYjyN8" },
    2: { episodeNumber: 2, episodeName: "Meet Brooke", fileName: "FINAL_BG_EPS02_Meet_Brooke_transcript_with_speakers.txt", id: "4ky9obFBItwg73ZWiwNq4z" },
    3: { episodeNumber: 3, episodeName: "Why the body?", fileName: "FINAL_BaG_EPS03_transcript_with_speakers.txt", id: "3bh9FZqsyuc5FeOTVa9f20" },
    4: { episodeNumber: 4, episodeName: "Debating Manifestation and Acceptance", fileName: "FINAL_BaG_EPS04_Law_Of_Attraction_transcript_with_speakers.txt", id: "2eedmLhi6L4Vsv6wd1gVdo" },
    5: { episodeNumber: 5, episodeName: "When Truth is a Pain in the Ass", fileName: "FINAL_BaG_EPS05_What_Is_True_transcript_with_speakers.txt", id: "2UpExKjK5bz0r1L7yGOnEb" },
    6: { episodeNumber: 6, episodeName: "What is Disembodiment About?", fileName: "FINAL_BaG_EPS06_What_Does_It_Mean_To_Disembody_transcript_with_speakers.txt", id: "5Fvu57AGvt6VqZ9z6VSdcR" },
    7: { episodeNumber: 7, episodeName: "Why Meditate", fileName: "FINAL_BaG_EPS07_Why_Meditate_transcript_with_speakers.txt", id: "6LGcxxbKXLrs1tsUE0QFIt" },
    8: { episodeNumber: 8, episodeName: "Psychology vs. Spirituality", fileName: "FINAL_BaG_EPS08_Psych_vs_Spirit_transcript_with_speakers.txt", id: "4nFfk4NtIQ4cFKh8iTLmZB" },
    9: { episodeNumber: 9, episodeName: "What's Self Love Got To Do With It?", fileName: "FINAL_BaG_EPS09_transcript_with_speakers.txt", id: "3UHXlwhw5D37l6oV2sEZU1" },
    10: { episodeNumber: 10, episodeName: "Self-Love In Action", fileName: "FINAL_BaG_EPS10_Self-Love_In_Action_transcript_with_speakers.txt", id: "2JvdgpRWxjLeMemNkSBhhO" },
    11: { episodeNumber: 11, episodeName: "On Spiritual Sensitivity", fileName: "FINAL_BaG_EPS11_Sensies_transcript_with_speakers.txt", id: "5KbDV3V2QQNR4ltTAmUJaJ" },
    12: { episodeNumber: 12, episodeName: "Getting Comfortable With Uncomfortable", fileName: "FINAL_BaG_EPS12_Comfortable_with_Uncomfortable_transcript_with_speakers.txt", id: "0wUYjM2n1WNC1j9wVJfOvA" },
    13: { episodeNumber: 13, episodeName: "Relating to Fear", fileName: "FINAL_BaG_EPS13_Relating_To_Fear_transcript_with_speakers.txt", id: "1O42NB1s0DPFpwuMoWI1wv" },
    14: { episodeNumber: 14, episodeName: "Unhooking From the Fear Crazy Train", fileName: "FINAL_BaG_EPS14_Fear_Part_Deux_transcript_with_speakers.txt", id: "75M2QuMgjDysvbUJKrDODz" },
    15: { episodeNumber: 15, episodeName: "How We Heal", fileName: "FINAL_BaG_EPS15_How_To_Heal_transcript_with_speakers.txt", id: "4l9zRrECib2CS1lpdTKLrb" },
    16: { episodeNumber: 16, episodeName: "Joy Phobia", fileName: "FINAL_BaG_EPS16_Fear_of_Joy_transcript_with_speakers.txt", id: "5esMune30Jqn21gytSh33I" },
    17: { episodeNumber: 17, episodeName: "What About Selfless Love?", fileName: "FINAL_BAG_EPS17_Sefless_Love_transcript_with_speakers.txt", id: "5fCwZexBaLIP0jHiQfGepo" },
    18: { episodeNumber: 18, episodeName: "Emotional Contagion", fileName: "FINAL_BaG_EPS18_Emotional_Contagion_transcript_with_speakers.txt", id: "0vTJSPdnynHnpkaJ4xSZG7" },
    19: { episodeNumber: 19, episodeName: "Karma", fileName: "FINAL_BaG_EPS19_Karma_transcript_with_speakers.txt", id: "6fIse08YOzfnga9qEQtixY" },
    20: { episodeNumber: 20, episodeName: "Big Me vs. Little Me", fileName: "FINAL_BaG_EPS20_Big_Me_Little_Me_transcript_with_speakers.txt", id: "3HtL30QUTxagAYCJ2IZBRf" },
    21: { episodeNumber: 21, episodeName: "The Ego", fileName: "FINAL_BaG_EPS21_The_Ego_transcript_with_speakers.txt", id: "5T6GltpfQ1ELmbeuYRQwvv" },
    22: { episodeNumber: 22, episodeName: "Groundlessness", fileName: "FINAL_BaG_EPS22_Groundlessness_transcript_with_speakers.txt", id: "594c2JmAusDEZeHWfhwIQn" },
    23: { episodeNumber: 23, episodeName: "Attachments and Desire", fileName: "FINAL_BaG_EPS23_Attachment_and_Desire_transcript_with_speakers.txt", id: "2u5rWKJBrUM3uhDbKxzMzf" },
    24: { episodeNumber: 24, episodeName: "Love and Relationships", fileName: "FINAL_BaG_EPS24_Love_and_Relationships_transcript_with_speakers.txt", id: "6FBilQWm8MNXVH40p965xo" },
    25: { episodeNumber: 25, episodeName: "Where to Begin", fileName: "FINAL_BG_EPS25_transcript_with_speakers.txt", id: "6y73g8y5KPrHX8dFT0bAVQ" },
    26: { episodeNumber: 26, episodeName: "The Gifts of Grief and Despair", fileName: "26_grief_and_despair.txt", id: "0yf16C30Xy5yJsXLjUb7Ri" },
    27: { episodeNumber: 27, episodeName: "Healing a Broken Heart", fileName: "FINAL_BaG_EPS27_Healing_A_Broken_Heart_transcript_with_speakers.txt", id: "34lOOX1a31nEi0dwHUy2CW" },
    28: { episodeNumber: 28, episodeName: "Chasing Happiness", fileName: "FINAL_BaG_EPS28_Chasing_Happiness_transcript_with_speakers.txt", id: "7whOaWHVLED7mF639l1NEA" },
    29: { episodeNumber: 29, episodeName: "How to Stop, Drop, and Feel", fileName: "FINAL_BG_EPS29_Emotional_Hygiene_transcript_with_speakers.txt", id: "5XTLZoDvIVIZFKd5QWfuAs" },
    30: { episodeNumber: 30, episodeName: "Seek Ease and Choose Pleasure", fileName: "FINAL_BG_EPS30_Seek_Ease_And_Choose_Pleasure_transcript_with_speakers.txt", id: "33uUKqXEqU8OC0LwegPvxS" },
    31: { episodeNumber: 31, episodeName: "Defining Boundaries", fileName: "FINAL_BG_EPS31_Boundaries_transcript_with_speakers.txt", id: "0BK48IhlCIxe5JKYdOA7bf" },
    32: { episodeNumber: 32, episodeName: "Holding Space for Not Knowing", fileName: "FINAL_BG_EPS32_Not_Knowing_transcript_with_speakers.txt", id: "33JUz4gSgo4iOOW14uqH57" },
    33: { episodeNumber: 33, episodeName: "The Self-Referencing Bubble", fileName: "FINAL_BG_EPS33_Pain_Bubble_transcript_with_speakers.txt", id: "6Y6o2YfbuKZb6OWAqcneUp" },
    35: { episodeNumber: 35, episodeName: "Pain Bodies in Action", fileName: "FINAL_BG_EPS35_Pain_Bodies_In_Action_transcript_with_speakers.txt", id: "1xFeL4RwyeKQ0JWrq6sCzo" },
    36: { episodeNumber: 36, episodeName: "Acceptance, Enjoyment, Enthusiasm", fileName: "FINAL_BG_EPS36_Accept_Enjoy_Enthu_transcript_with_speakers.txt", id: "0GiY22luqjuAlI5UsFwGs8" },
    37: { episodeNumber: 37, episodeName: "Self-Compassion Along The Way", fileName: "FINAL_BG_EPS37_Self_Compassion_transcript_with_speakers.txt", id: "1gsv1RoQzViv6hzgnUeGKd" },
    38: { episodeNumber: 38, episodeName: "The Importance of Community", fileName: "FINAL_BG_EPS38_Community_transcript_with_speakers.txt", id: "6vHBEgzycK4WyD6Wi4WDvq" },
    39: { episodeNumber: 39, episodeName: "Self-Compassion Part 2", fileName: "FINAL_BG_EPS39_Dear_Bliss_and_Grit_transcript_with_speakers.txt", id: "2yzAPSOgIq33NNhkZI7huM" },
    40: { episodeNumber: 40, episodeName: "Identity Crisis", fileName: "FINAL_BG_EPS40_Identity_Crisis_transcript_with_speakers.txt", id: "1i2UFi0ieP041oMgpXJSar" },
    41: { episodeNumber: 41, episodeName: "The Realization Process", fileName: "", id: "3uiBOOXsRBEFTmTwHf4iyO" },
    42: { episodeNumber: 42, episodeName: "The Dynamics of Energy", fileName: "FINAL_BG_EPS42_Energy_transcript_with_speakers.txt", id: "4cd0R06lwiOtmpQ9KwxS6w" },
    43: { episodeNumber: 43, episodeName: "Life as an Empath", fileName: "FINAL_BG_EPS43_Life_As_An_Empath_transcript_with_speakers.txt", id: "1D6M5tfiBAzSP4Puqew6Qq" },
    44: { episodeNumber: 44, episodeName: "The Subtle Edges of Relationship", fileName: "FINAL_BG_EPS44_Dear_BG_transcript_with_speakers.txt", id: "0Mf7qkhbpOYF5vRv2DMIqU" },
    45: { episodeNumber: 45, episodeName: "Purpose", fileName: "FINAL_BG_EPS45_Purpose_transcript_with_speakers.txt", id: "0WHUCkQoaw0gKqIutqL8Hw" },
    46: { episodeNumber: 46, episodeName: "Trust Your Life", fileName: "FINAL_BG_EPS46_Living_From_Truth_transcript_with_speakers.txt", id: "7npZZNtK7jYzY7koxfX1I1" },
    48: { episodeNumber: 48, episodeName: "Body as Object or Body as Self?", fileName: "48_Body_AS_Self.txt", id: "0Y9JcwG6ew7T0WtFSyYURE" },
    49: { episodeNumber: 49, episodeName: "The Need for Approval", fileName: "FINAL_BG_EPS49_Need_For_Approval_transcript_with_speakers.txt", id: "6D6AKKjQMna6EvlxFkATIK" },
    50: { episodeNumber: 50, episodeName: "Actually Loving What Arises", fileName: "FINAL_BG_EPS50_Actually_Loving_What_Arises_transcript_with_speakers.txt", id: "2M7BmBtdNm7suwu2JETni7" },
    51: { episodeNumber: 51, episodeName: "The Awakening Nervous System", fileName: "FINAL_BG_EPS51_The_Nervous_System_transcript_with_speakers.txt", id: "5ycUAY1Qbj2sGLzjePlYr7" },
    52: { episodeNumber: 52, episodeName: "Attachment Issues and Spirituality", fileName: "FINAL_D2_BG_EPS52_Attachment_Issues_transcript_with_speakers.txt", id: "1RDVyxiEYR2Oq3RjOb5jhl" },
    53: { episodeNumber: 53, episodeName: "Awakening FOMO", fileName: "FINAL_BG_EPS53_Awakening_FOMO_transcript_with_speakers.txt", id: "4eqruPC0fdX7ubDAHtJqp3" },
    54: { episodeNumber: 54, episodeName: "The Spiritual Path is Not a Benzo", fileName: "FINAL_BG_EPS54_Clarity_Love_Fulfillment_transcript_with_speakers.txt", id: "2iMW1A8Vr1YzYVYgIUvEJE" },
    55: { episodeNumber: 55, episodeName: "Hearing the Unseen Worlds", fileName: "FINAL_BG_EPS55_Unseen_Worlds_transcript_with_speakers.txt", id: "3IgBrmay5frcD0gPOHQgAW" },
    56: { episodeNumber: 56, episodeName: "Mercy to the Humans: A Conversation With Jeannie Zandi", fileName: "", id: "2XtXRzraH6UCfYTk5YZ15k" },
    57: { episodeNumber: 57, episodeName: "Groundlessness Again?", fileName: "FINAL_BG_EPS57_Not_Pinning_Down_transcript_with_speakers.txt", id: "5wUCbTFWdbHAACOvhHQuAq" },
    58: { episodeNumber: 58, episodeName: "Over-Identifying with the Body", fileName: "FINAL_BG_EPS58_transcript_with_speakers.txt", id: "30JNlagQX3VUmRJbLKlyyQ" },
    59: { episodeNumber: 59, episodeName: "On Making Yourself a Problem", fileName: "FINAL_BG_EPS59_Problem_Self_transcript_with_speakers.txt", id: "2QZRS0Xw7PHjCL6pCJ13LI" },
    60: { episodeNumber: 60, episodeName: "Are We Responsible for Others?", fileName: "FINAL_BG_EPS60_Are_We_Responsible_For_Others_transcript_with_speakers.txt", id: "4sB3OyqCO34EbU8L1X61wO" },
    61: { episodeNumber: 61, episodeName: "Should We Focus on Positivity?", fileName: "FINAL_BG_EPS61_Positivity_transcript_with_speakers.txt", id: "5Gc1nJDCGFnFr32gcc6B5S" },
    62: { episodeNumber: 62, episodeName: "Extraordinarily Ordinary", fileName: "FINAL_BG_EPS62_Extraordinarily_Ordinary_transcript_with_speakers.txt", id: "49SU6ZSIEQCtERVTRolTgp" },
    63: { episodeNumber: 63, episodeName: "Living From the Heart: A Conversation with John J. Prendergast", fileName: "", id: "0Y7Qy5KJiiUaBnCCQE7NK1" },
    64: { episodeNumber: 64, episodeName: "On Aliveness", fileName: "FINAL_BG_EPS64_On_Aliveness_transcript_with_speakers.txt", id: "3KfMoGuqrtzQlhMmVPTvcj" },
    65: { episodeNumber: 65, episodeName: "What if It's Not a Problem?", fileName: "FINAL_BG_EPS65_transcript_with_speakers.txt", id: "5xnzv5f6WtxQEV8gcBLUcd" },
    66: { episodeNumber: 66, episodeName: "Everything is Welcome Here: Reflections on a Weekend with Matt Kahn", fileName: "FINAL_BG_EPS66_Matt_Kahn_Weekend_transcript_with_speakers.txt", id: "1HaV96F4aRdIFYyjUK5Zcd" },
    67: { episodeNumber: 67, episodeName: "Ancestry, Heart, and Instinct: A Conversation with John Lockley", fileName: "", id: "2tp3PQpNlDxTHqpuk0Yunj" },
    68: { episodeNumber: 68, episodeName: "Meditation and Song with John Lockley", fileName: "", id: "2y74ZbCq5GfM9RcDekBlUd" },
    69: { episodeNumber: 69, episodeName: "Bringing Through Your Purpose: A Conversation with Lissa Boles", fileName: "", id: "3fNlqT9P6Vc4krhrPhozDr" },
    70: { episodeNumber: 70, episodeName: "Forgiveness", fileName: "FINAL_BG_EPS70_Forgiveness_transcript_with_speakers.txt", id: "6fF0EA6Dhb2OPcrAq3PpwT" },
    71: { episodeNumber: 71, episodeName: "True Belonging", fileName: "", id: "3yIIgmOteDyCG7Hmi99jcc" },
    72: { episodeNumber: 72, episodeName: "Being with the Darkness", fileName: "FINAL_BG_EPS72_Being_With_Darkness_transcript_with_speakers.txt", id: "32ZlvJp1xiCkzyRGb36MYZ" },
    73: { episodeNumber: 73, episodeName: "The Micro-shaming Epidemic", fileName: "FINAL_BG_EPS73_Micro_Shaming_transcript_with_speakers.txt", id: "0YKaNPlblFGjozXCCP8rQh" },
    74: { episodeNumber: 74, episodeName: "Psychological Agendas", fileName: "FINAL_BG_EPS74_Agendas_transcript_with_speakers.txt", id: "7epj1B8FHyLwuO0BOq4IzF" },
    75: { episodeNumber: 75, episodeName: "Ending the Search: A Conversation with Dorothy Hunt", fileName: "", id: "5Or1hTpmHxemrM7kP09Tbt" },
    76: { episodeNumber: 76, episodeName: "Spiritual Bypass", fileName: "FINAL_BG_EPS76_Spiritual_Bypassing_transcript_with_speakers.txt", id: "63LovFVDtvFK0DgQm8rL1H" },
    77: { episodeNumber: 77, episodeName: "Fully Awake and Fully Human; A Conversation with Amoda Maa", fileName: "", id: "200GRGnaVvBOFFZYCYZSgh" },
    78: { episodeNumber: 78, episodeName: "Overemphasizing Suffering", fileName: "FINAL_BG_EPS78_Suffering_As_Bypass_transcript_with_speakers.txt", id: "0IlDtTRHZY8RtYxOuG2PI0" },
    79: { episodeNumber: 79, episodeName: "Sacred Vigilance", fileName: "FINAL_BG_EPS79_Sacred_Vigilance_transcript_with_speakers.txt", id: "07Cc2kBC3RAjgg2MODW9ma" },
    80: { episodeNumber: 80, episodeName: "I Don't Know", fileName: "FINAL_BG_EPS80_I_Dont_Know_transcript_with_speakers.txt", id: "5Bjr6eVe6zRWUwG1jlelH3" },
    81: { episodeNumber: 81, episodeName: "Meeting Anger", fileName: "", id: "78P2eM0TWzfHH16z2UZorO" },
    82: { episodeNumber: 82, episodeName: "The Art of Shifting: A Conversation with Loch Kelly", fileName: "", id: "4SsTjhuWlm7tddMJa2ZFZR" },
    83: { episodeNumber: 83, episodeName: "The Awakening Nervous System Part 2", fileName: "FINAL_BG_EPS83_Nervous_System_Part_Deux_transcript_with_speakers.txt", id: "36HCYU9cGSMCW9yFjHyhtP" },
    84: { episodeNumber: 84, episodeName: "Everything is Here to Help You: A Conversation with Matt Kahn", fileName: "", id: "7tPqKqRbAAZiq7rWFLtFZF" },
    85: { episodeNumber: 85, episodeName: "Exploring the Similarities Between Teachings", fileName: "FINAL_BG_EPS85_Loch_and_Matt_mash_up_transcript_with_speakers.txt", id: "4MYnUdVRhsuuWcyPWVB4c1" },
    87: { episodeNumber: 87, episodeName: "Turning Towards Our Triggers", fileName: "FINAL_BG_EPS87_Angry_Dogs_transcript_with_speakers.txt", id: "2pedz5TlPe3rzLUxGxFwkV" },
    88: { episodeNumber: 88, episodeName: "The Power of Words", fileName: "FINAL_BG_EPS88_Power_of_Words_transcript_with_speakers.txt", id: "46BB35Au1MLZHWLVPtIj2x" },
    89: { episodeNumber: 89, episodeName: "Our Bliss + Grit Journey", fileName: "FINAL_BG_EPS89_2_Years_transcript_with_speakers.txt", id: "6U2O0OfLNUf7Guil7gm45q" },
    90: { episodeNumber: 90, episodeName: "Why Talk About Awakening?", fileName: "FINAL_BG_EPS90_Awakening_transcript_with_speakers.txt", id: "42b9mNG9iG3HMMJ4OGzHq9" },
    91: { episodeNumber: 91, episodeName: "The Implications of Basic Trust", fileName: "FINAL_BG_EPS91_Basic_Trust (6)_transcript_with_speakers.txt", id: "5bip96Ea2sjmXhRAiKVnTz" },
    92: { episodeNumber: 92, episodeName: "Radical Gratitude: A Conversation with Will Pye", fileName: "", id: "7DQNVTBoSZPxoQ6mgjOHQ6" },
    93: { episodeNumber: 93, episodeName: "Gradual Awakening; A Conversation with Miles Neale", fileName: "", id: "5GiPKVfwzvjmGnvLYBlPbN" },
    94: { episodeNumber: 94, episodeName: "Working with What Feels Unworkable", fileName: "FINAL_BG_EPS94_Hell_Realms_transcript_with_speakers.txt", id: "6EzQxXi5bdvFf5TZaXdIjf" },
    95: { episodeNumber: 95, episodeName: "Embodying Yin: A Conversation with Jeannie Zandi", fileName: "", id: "0wadazW5MIWKrY3g8efPCH" },
    96: { episodeNumber: 96, episodeName: "Allowing Heaven: A Conversation with David Thomas", fileName: "", id: "5DATy2Pzxj2MAiKqhxkEXN" },
    97: { episodeNumber: 97, episodeName: "What If It's All Conditioning?", fileName: "FINAL_BG_EPS97_All_Conditioning_transcript_with_speakers.txt", id: "311X3VOW5iCLvM1emEpPY7" },
    98: { episodeNumber: 98, episodeName: "Being Presence: A Conversation with Neelam", fileName: "", id: "2dccjkGvASLb9qIPoIKEYG" },
    99: { episodeNumber: 99, episodeName: "Shifting Co-Dependency", fileName: "FINAL_BG_EPS99_transcript_with_speakers.txt", id: "0D0g6vlLR78GqrqpzRaf4T" },
    100: { episodeNumber: 100, episodeName: "The Good News", fileName: "FINAL_D2_BG_EPS100_Good_News_transcript_with_speakers.txt", id: "5CyFaU3pEzEVHL321mejXv" },
    101: { episodeNumber: 101, episodeName: "Can We Create Through Language?", fileName: "FINAL_BG_EPS101_Language_transcript_with_speakers.txt", id: "4Zire468YMi5lqRkFiUIMU" },
    102: { episodeNumber: 102, episodeName: "Healing the Limbic System", fileName: "FINAL_BG_EPS102_DNRS_transcript_with_speakers.txt", id: "4HwslSPRA2gixNL67Ti93o" },
    103: { episodeNumber: 103, episodeName: "On Trauma and the Unbound Body; A Conversation with Judith Blackstone", fileName: "", id: "1TA4hykrxu2Nw5XmQLe4hn" },
    104: { episodeNumber: 104, episodeName: "Turn Towards or Turn Away?", fileName: "Ep_104__Turn_Towards_or_Turn_Away_transcript_with_speakers.txt", id: "6NMJEHKKCCV1Iy9luxvQym" },
    105: { episodeNumber: 105, episodeName: "A New Vision for Relationship: A Conversation with Amoda Maa and Kavi Jezzie Hockaday", fileName: "", id: "54YZwu49bSHzNYzCYqPtF6" },
    106: { episodeNumber: 106, episodeName: "Co-Creation", fileName: "BG-106_Project_Podcast_Co-Creation_transcript_with_speakers.txt", id: "4YtJyxhYQQvX5GdVUODQUd" },
    107: { episodeNumber: 107, episodeName: "The Nitty Gritty of Transformation", fileName: "BG-107_The_Nitty_Gritty_of_Transformation_transcript_with_speakers.txt", id: "3GPIC8SmOMYomod1m6i3tc" },
    108: { episodeNumber: 108, episodeName: "Vision Pulls You", fileName: "BG-108_Project_Podcast_Audio_v1_1_1_transcript_with_speakers.txt", id: "2z3Ne70vrPV53E2Is4PMKc" },
    109: { episodeNumber: 109, episodeName: "The Subtle Impacts of Judgment", fileName: "BG-109_Project_Podcast_Audio_v2_0_0_transcript_with_speakers.txt", id: "2qBXJXGcwhaN8B6zWHlqo7" },
    110: { episodeNumber: 110, episodeName: "Surrendering the Burden", fileName: "BG-110_Project_Podcast_Audio_v1_1_0_transcript_with_speakers.txt", id: "6Zd0AMSEpgM53E78dm8fDX" },
    111: { episodeNumber: 111, episodeName: "Knowing Is Not Enough", fileName: "BG-111_Project_Podcast_Knowing_Is_Not_Enough_transcript_with_speakers.txt", id: "2wqmhKVLzleDV1Iw5k0pBX" },
    112: { episodeNumber: 112, episodeName: "Everything is Here to Help You [Flashback Tuesday]", fileName: "", id: "792tNT0yF85HKV1eZjF5eP" },
    113: { episodeNumber: 113, episodeName: "Taking the Vertical Path", fileName: "BG-113_Project_Podcast_Taking_The_Vertical_Path_transcript_with_speakers.txt", id: "7EGlD50aqlYCKpbzcnoRuZ" },
    114: { episodeNumber: 114, episodeName: "Awakened Relating: A Conversation with Lynn Marie Lumiere", fileName: "", id: "48qAxIP2Vwqy7sHgAtRzaY" },
    115: { episodeNumber: 115, episodeName: "How to Heal With Self-Love", fileName: "Ep_115__How_to_Heal_With_Self-Love_transcript_with_speakers.txt", id: "2xPhYqdfFPjXfTOlYLMZbV" },
    116: { episodeNumber: 116, episodeName: "Finding Safety", fileName: "Ep_116__Finding_Safety_transcript_with_speakers.txt", id: "7uPq7juQAsOY4JGVnjoTxB" },
    117: { episodeNumber: 117, episodeName: "Presence as a Love Language", fileName: "Ep_117__Presence_as_a_Love_Language_transcript_with_speakers.txt", id: "6tVHgTIMsyY5oiH9ISzS3U" },
    118: { episodeNumber: 118, episodeName: "Basic Trust [Flashback Tuesday]", fileName: "", id: "7dJdlaBJmXwA8uHimLAIzB" },
    119: { episodeNumber: 119, episodeName: "Spiritual Teacher Misconduct", fileName: "Ep_119__Guru_Misconduct_transcript_with_speakers.txt", id: "32Ui2aR7yG4h4y9FFcoxRM" },
    120: { episodeNumber: 120, episodeName: "When the Rules Don't Apply", fileName: "Ep_120__When_the_Rules_Don_t_Apply_transcript_with_speakers.txt", id: "1uSdixQIlgvjb8MQDPbz79" },
    121: { episodeNumber: 121, episodeName: "Fear of Being \"Too Much\"", fileName: "Ep_121__Fear_of_Being__Too_Much__transcript_with_speakers.txt", id: "4ReAniQY4le1SpZT3YUl4q" },
    122: { episodeNumber: 122, episodeName: "Neurosculpting: A Conversation with Lisa Wimberger [Part 1]", fileName: "", id: "7wy0eGgAQhDd5nIcgVFoAt" },
    123: { episodeNumber: 123, episodeName: "Neurosculpting: A Conversation with Lisa Wimberger [Part 2]", fileName: "", id: "0623eOuHQthRHfeIZx8X3m" },
    124: { episodeNumber: 124, episodeName: "The Gratitude Prescription: A Conversation with Will Pye [Part 1]", fileName: "", id: "59ktm6cITGtItt3rfm7lJa" },
    125: { episodeNumber: 125, episodeName: "The Gratitude Prescription: A Conversation with Will Pye [Part 2]", fileName: "", id: "4HM1cpYJXh7CHMDcm3r2cl" },
    126: { episodeNumber: 126, episodeName: "The Fawn Response", fileName: "FinalBaG_126_The_Fawn_Response.txt", id: "0ZlxlmxADN5osILUycjPwV" },
    127: { episodeNumber: 127, episodeName: "Energy Medicine: A Conversation with Jill Blakeway", fileName: "", id: "0zG78zNBR0ZHuoXup40XET" },
    128: { episodeNumber: 128, episodeName: "Our View of Healing and Transformation", fileName: "Ep_128__Our_View_of_Healing_and_Transformation_transcript_with_speakers.txt", id: "24kdEES9IEzjYyxBaM7s3R" },
    129: { episodeNumber: 129, episodeName: "The Art of Shifting: A Conversation with Loch Kelly [Flashback Tuesday]", fileName: "", id: "7qEFhjqmYSUxwf3pw73l4V" },
    130: { episodeNumber: 130, episodeName: "Living From the Heart: A Conversation with John J. Prendergast [Flashback Tuesday]", fileName: "", id: null },
    131: { episodeNumber: 131, episodeName: "Allowing Heaven: A Conversation with David Thomas [Flashback Tuesday]", fileName: "", id: null },
    132: { episodeNumber: 132, episodeName: "What If It's All Conditioning? [Flashback Tuesday]", fileName: "", id: null },
    133: { episodeNumber: 133, episodeName: "Being Presence: A Conversation with Neelam [Flashback Tuesday]", fileName: "", id: null },
    134: { episodeNumber: 134, episodeName: "Embodying Yin: A Conversation with Jeannie Zandi [Flashback Tuesday]", fileName: "", id: null },
    135: { episodeNumber: 135, episodeName: "Meet Vanessa [Throwback Tuesday]", fileName: "", id: null },
    136: { episodeNumber: 136, episodeName: "Meet Brooke [Flashback Tuesday]", fileName: "", id: null },
    137: { episodeNumber: 137, episodeName: "Suffering is Optional: A Conversation with Gail Brenner", fileName: "", id: null },
    138: { episodeNumber: 138, episodeName: "Living From Truth", fileName: "Ep_138__Living_From_Truth_transcript_with_speakers.txt", id: null },
    139: { episodeNumber: 139, episodeName: "Untangling the Imaginary Audience", fileName: "Ep_139__Untangling_the_Imaginary_Audience_transcript_with_speakers.txt", id: null },
    140: { episodeNumber: 140, episodeName: "From Fawn to Fierce: A Conversation with Jane Clapp", fileName: "", id: null },
    141: { episodeNumber: 141, episodeName: "Why Does Deep Emotion Feel Overwhelming?", fileName: "BG-141_Project_Podcast_Audio_v1_0_2r3-Live10.1_transcript_with_speakers.txt", id: null },
    143: { episodeNumber: 143, episodeName: "Ideas About Awakening", fileName: "FINAL_BG_EPS143_transcript_with_speakers.txt", id: "7hiwgfTJHeNgY2li6zvuQY" },
    144: { episodeNumber: 144, episodeName: "Or Maybe You're Perceiving Something Accurately?", fileName: "FINAL_BG_EPS144_transcript_with_speakers.txt", id: "1dlPgc1CKu5InNfRsnqVPk" },
    145: { episodeNumber: 145, episodeName: "When Change Comes to Something You Love", fileName: "FINAL_BG_EPS145_transcript_with_speakers.txt", id: "7FvQc0R9Alw87wqhW1twqE" },
    146: { episodeNumber: 146, episodeName: "The Deep Heart with John Prendergast", fileName: "", id: "1GcmrAOhZhRpefKqd8naTO" },
    147: { episodeNumber: 147, episodeName: "From Codependence to Interdependence", fileName: "FINAL_BG_EPS147_transcript_with_speakers.txt", id: "5fl4330FjddkaUU4SHKLUo" },
    148: { episodeNumber: 148, episodeName: "Healing the Lineage", fileName: "FINAL_BG_EPS148_transcript_with_speakers.txt", id: "25eC8fLxaLTkSeR5nKmHMQ" },
    149: { episodeNumber: 149, episodeName: "What is Trauma?", fileName: "FINAL_BG_EPS149_LBeing_transcript_with_speakers.txt", id: "60tK8lDN1PT0BUcGvfvZDJ" },
    150: { episodeNumber: 150, episodeName: "Can We Bio-Hack Ourselves into Better States of Mind and Being?", fileName: "FINAL_BG_EPS150_Bio_hack_transcript_with_speakers.txt", id: "5GMRCgFNFNrxr40rOImzOl" },
    151: { episodeNumber: 151, episodeName: "Spiritual Maturity and Surrender: A Conversation with Matt Kahn", fileName: "FINAL_BG_EPS151_Matt_Kahn_transcript_with_speakers.txt", id: "5d5tdVmVeKalZS1i2yvvJj" },
    152: { episodeNumber: 152, episodeName: "You're Not Doing Anything Wrong", fileName: "FINAL_BG_EPS152_You're_Not_Doing_Anything_Wrong_transcript_with_speakers.txt", id: "2awfwoLqqNQBn8hyHVjitg" },
    153: { episodeNumber: 153, episodeName: "A Fond Farewell and What's Next", fileName: "", id: "4BQBDnGx9z0YmYayn6zQJy" }
}

module.exports = { episodeMap };

// You can add this conditional export for ES modules compatibility if needed later
if (typeof exports !== 'undefined') {
    Object.defineProperty(exports, '__esModule', { value: true });
}